name: CI

on: [push]

jobs:
  OSX:

    runs-on: macOS-10.14

    steps:
    - name: Checkout Source
      uses: actions/checkout@v1
    
    - name: Install Dependencies
      run: |
        brew install llvm
    
    - name: Build and test
      run: |
        export PATH=$(brew --prefix llvm)/bin:$PATH
        export CC=clang
        export CXX=clang++
        export CODEBUILD_SRC_DIR=$(pwd)
        python3 -c "from urllib.request import urlretrieve; urlretrieve('https://raw.githubusercontent.com/awslabs/aws-c-common/master/codebuild/builder.py', 'builder.py')"
        python3 builder.py build macos-default-default-macos-x64
